# Generated by Django 2.1.2 on 2018-10-18 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurants_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('price', models.CharField(max_length=300)),
                ('rating', models.CharField(max_length=300)),
                ('image', models.CharField(max_length=300)),
                ('check', models.IntegerField()),
            ],
        ),
    ]
