# Generated by Django 2.1.2 on 2018-10-19 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurants_info',
            name='check',
            field=models.CharField(max_length=300),
        ),
    ]
