# Generated by Django 2.1.2 on 2018-10-19 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0003_auto_20181019_0020'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurants_info',
            name='selected',
            field=models.CharField(default='', max_length=300),
        ),
    ]
