# Generated by Django 2.1.2 on 2018-10-23 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0004_restaurants_info_selected'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurants_info',
            name='address',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='restaurants_info',
            name='phone',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AddField(
            model_name='restaurants_info',
            name='url',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
