# Generated by Django 2.1.2 on 2018-10-24 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0005_auto_20181023_0546'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurants_info',
            name='session_key',
            field=models.CharField(default='', max_length=300),
        ),
    ]
