# Generated by Django 2.1.2 on 2018-10-24 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0006_restaurants_info_session_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurants_info',
            name='session_key',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
